#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinydashboard)

dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)

shinyUI(dashboardPage(
  skin = "blue",
  dashboardHeader(title = "Control de Límites",
                  titleWidth = 300),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Carga de datos ", tabName = "carga", icon = icon("upload", lib = "glyphicon")),
      menuItem("Boxplot Facturación Anual", tabName = "boxplot_tas", icon = icon("object-align-vertical", lib = "glyphicon")),
      menuItem("Histograma Facturación Anual", tabName = "histogra_tas", icon = icon("stats", lib = "glyphicon"))#el icon signal tambien queda bien
    )
  ),
  dashboardBody(
    tags$head(tags$style(HTML('
      .main-header .logo {
        font-family: "Georgia", Times, "Times New Roman", serif;
        font-weight: bold;
        font-size: 24px;
      }
    '))),
    tabItems(
      tabItem(tabName = "carga",#----
              fluidRow(
                box(img(src = "logo_empresa.jpg", height = 110, width = 750),
                    background = NULL,
                    width = 6),
                box(title = "Seleccionar zona",
                    selectInput(inputId = "zona_selec",
                                label = "", 
                                choices = zonas_vector,
                                selected = "A"),
                    width = 6,
                    status = "primary",
                    #                    background = "orange",
                    solidHeader = T,
                    collapsible = FALSE),
                box(title = "Datos de Mercado",
                    fileInput(inputId = "carga_mercado",
                              label = "Resultados de Consultora",
                              buttonLabel = "Cargar archivo excel...",
                              multiple = FALSE,
                              placeholder = "Ningun archivo fue seleccionado", 
                              accept = c(".xlsx")),
                    width = 6,
                    status = "primary",
                    solidHeader = F),
                box(title = "Porcentaje de Aumento Mediana del mercado según grupo",
                    footer = "Ingresar valores en % y con punto como separador decimal",
                    numericInput(inputId = "porc_g1",
                                 label = "% grupo 1",
                                 value = 25),
                    numericInput(inputId = "porc_g2",
                                 label = "% grupo 2",
                                 value = 25),
                    numericInput(inputId = "porc_g3",
                                 label = "% grupo 3",
                                 value = 25),
                    numericInput(inputId = "porc_g4",
                                 label = "% grupo 4",
                                 value = 25),
                    width = 6,
                    status = NULL,
                    solidHeader = F,
                    collapsible = T,
                    collapsed = T),
                box(title = "Elementos para Transformación del Mercado",
                    footer = "Ingresar valores en % y con punto como separador decimal",
                    numericInput(inputId = "env",
                                 label = "Coef. Envejecimiento",
                                 value = 2.5),
                    numericInput(inputId = "coef_a",
                                 label = "Coef. A",
                                 value = 4),
                    numericInput(inputId = "coef_b",
                                 label = "Coef. B",
                                 value = 20),
                    numericInput(inputId = "coef_c1",
                                 label = "Coef. C grupo 1",
                                 value = 1.2),
                    numericInput(inputId = "coef_c2",
                                 label = "Coef. C grupo 2",
                                 value = 2.6),
                    numericInput(inputId = "coef_c3",
                                 label = "Coef. C grupo 3",
                                 value = 2.8),
                    numericInput(inputId = "coef_c4",
                                 label = "Coef. C grupo 4",
                                 value = 3.1),
                    width = 6,
                    status = NULL,
                    solidHeader = F,
                    collapsible = T,
                    collapsed = T),
                box(title = "Coef. D según nivel",
                    footer = "Ingresar valores en % y con punto como separador decimal", #INTENTAR PODER INGRESAR CON COMA COMO SEP DECIMAL
                    numericInput(inputId = "coef_d_m4a4",
                                 label = "Coef. D, nivel -4 a 4",
                                 value = 4), #todos los target ipb para cada cat ----
                    numericInput(inputId = "coef_d_5a7",
                                 label = "Coef. D, nivel 5 a 7",
                                 value = 6),
                    numericInput(inputId = "coef_d_8",
                                 label = "Coef. D, nivel 8",
                                 value = 8),
                    numericInput(inputId = "coef_d_9",
                                 label = "Coef. D, nivel 9",
                                 value = 11),
                    numericInput(inputId = "coef_d_10",
                                 label = "Coef. D, nivel 10",
                                 value = 15),
                    numericInput(inputId = "coef_d_11",
                                 label = "Coef. D, nivel 11",
                                 value = 19),
                    numericInput(inputId = "coef_d_12",
                                 label = "Coef. D, nivel 12",
                                 value = 20),
                    numericInput(inputId = "coef_d_13",
                                 label = "Coef. D, nivel 13",
                                 value = 22),
                    numericInput(inputId = "coef_d_14",
                                 label = "Coef. D, nivel 14",
                                 value = 22),
                    numericInput(inputId = "coef_d_15",
                                 label = "Coef. D, nivel 15",
                                 value = 25),
                    numericInput(inputId = "coef_d_16",
                                 label = "Coef. D, nivel 16",
                                 value = 30),
                    numericInput(inputId = "coef_d_17",
                                 label = "Coef. D, nivel 17",
                                 value = 30),
                    numericInput(inputId = "coef_d_18",
                                 label = "Coef. D, nivel 18",
                                 value = 30),
                    numericInput(inputId = "coef_d_19",
                                 label = "Coef. D, nivel 19",
                                 value = 30),
                    numericInput(inputId = "coef_d_20",
                                 label = "Coef. D, nivel 20",
                                 value = 40),
                    numericInput(inputId = "coef_d_21",
                                 label = "Coef. D, nivel 21",
                                 value = 40),
                    numericInput(inputId = "coef_d_22", #----
                                 label = "Coef. D, nivel 22",
                                 value = 40),
                    width = 6,
                    status = NULL,
                    solidHeader = F,
                    collapsible = T,
                    collapsed = T),
                box(title = "Límites Actuales",
                    fileInput(inputId = "carga_orig",
                              label = NULL,
                              buttonLabel = "Cargar archivo excel...",
                              multiple = FALSE,
                              placeholder = "Ningun archivo fue seleccionado", 
                              accept = c(".xlsx")),
                    width = 6,
                    status = "danger",
                    solidHeader = T),
                box(title = "Límites Propuestos",
                    fileInput(inputId = "carga_prop",
                              label = NULL,
                              buttonLabel = "Cargar archivo excel...",
                              multiple = FALSE,
                              placeholder = "Ningun archivo fue seleccionado", 
                              accept = c(".xlsx")),
                    width = 6,
                    status = "success",
                    solidHeader = T),
                box(reactableOutput("tabla_inicial"),
                    width = 12,
                    status = "info"),
                box(title = "Parámetros para la Regresión del Mercado a nivel de la empresa",
                    prettyRadioButtons(inputId = "modelo_selec",
                                       label = "Elegir modelo",
                                       choices = c("Modelo Exponencial", "Modelo Cuadrático"),
                                       selected = "Modelo Exponencial",
                                       status = "primary",
                                       shape = c("square"),
                                       animation = "smooth",
                                       outline = T,
                                       thick = T,
                                       plain = F,
                                       inline = T),
                    numericRangeInput(inputId = "rango_corte_1",
                                      label = "Elegir rango nivel primer corte",
                                      value = c(1, 14),
                                      separator = " hasta ",
                                      min = 1,
                                      max = 14,
                                      step = 1),
                    numericRangeInput(inputId = "rango_corte_2",
                                      label = "Elegir rango nivel segundo corte",
                                      value = c(NA, NA),
                                      separator = " hasta ",
                                      min = 1,
                                      max = 14,
                                      step = 1),
                    numericRangeInput(inputId = "rango_corte_3",
                                      label = "Elegir rango nivel tercer corte",
                                      value = c(NA, NA),
                                      separator = " hasta ",
                                      min = 1,
                                      max = 14,
                                      step = 1),
                    width = 7),
                box(title = "Validación de Regresión",
                    reactableOutput("validacion_reg"), 
                    width = 5),
                box(title = "Gráfico Regresión del Mercado a nivel de la empresa",
                    plotlyOutput("grafico_reg"),
                    width = 12)
              )),
      tabItem(tabName = "boxplot_tas",#----
              fluidRow(
                box(title = "Seleccionar variante de boxplot a visualizar",
                    selectInput(inputId = "boxplot_selec",
                                label = "", 
                                choices = boxp_sel,
                                selected = "Boxplot comparando límites teóricos con estadisticas"),
                    width = 12,
                    status = "info",
                    solidHeader = T,
                    collapsible = TRUE),
                box(plotlyOutput("distPlot"),
                    title = "Facturación Anual",
                    width = 12,
                    status = "primary",
                    solidHeader = TRUE),
                box(img(src = "imagen_explic_boxplot.jpeg", height = 300, width = 300),
                    title = "Ayuda boxplots",
                    status = "info",
                    width = 5,
                    collapsible = T,
                    collapsed = T),
                box(title = "Seleccionar nivel a visualizar",
                    checkboxGroupInput(inputId = "nivel",
                                       label = "",
                                       choices = nivel_vector,
                                       selected = nivel_vector,
                                       inline = TRUE),
                    width = 7,
                    status = "info",
                    solidHeader = F,
                    collapsible = TRUE,
                    collapsed = T),
                box(DT::dataTableOutput("tabla_outliers"),
                    title = "Personas que son outliers estadisticos",
                    width = 12,
                    status = "primary",
                    solidHeader = TRUE,
                    collapsible = TRUE,
                    collapsed = TRUE)
              )
      ),
      tabItem(tabName = "histogra_tas",#----
              fluidRow(
                box(title = "Seleccionar nivel a visualizar",
                    radioButtons(inputId = "nivel_hist",
                                       label = "",
                                       choices = nivel_vector,
                                       selected = 8,
                                       inline = TRUE),
                    width = 12,
                    status = "info",
                    solidHeader = TRUE,
                    collapsible = TRUE),
                box(plotlyOutput("histPlot"),
                    title = "Facturación Anual",
                    width = 12,
                    status = "primary",
                    solidHeader = TRUE),
                box(reactableOutput("tabla_contingencia_orig_salida"),
                    title = "Cantidades límites ACTUALES",
                    width = 6,
                    status = "info",
                    solidHeader = T,
                    collapsible = TRUE,
                    collapsed = F),
                box(reactableOutput("tabla_contingencia_prop_salida"), 
                    title = "Cantidades límites PROPUESTOS",
                    width = 6,
                    status = "info",
                    solidHeader = T,
                    collapsible = T,
                    collapsed = F),
                box(plotOutput("barras_totales_Q"), 
                    shinyWidgets::sliderTextInput(inputId = "nivel_barras",
                                                  label = "Seleccionar rango de niveles para visualizar posicionamiento:", 
                                                  choices = 1:14,
                                                  selected = c(1, 14),
                                                  grid = T),
                    title = "",
                    width = 12,
                    status = "info",
                    solidHeader = F,
                    collapsible = F),
                box(DT::dataTableOutput("tabla_bajo_lim_teo_orig"),
                    title = "Personas Bajo Piso en límites actuales",
                    width = 12,
                    status = "danger",
                    solidHeader = F,
                    collapsible = TRUE,
                    collapsed = TRUE),
                box(DT::dataTableOutput("tabla_sobre_lim_teo_orig"),
                    title = "Personas Sobre Piso en límites actuales",
                    width = 12,
                    status = "danger",
                    solidHeader = F,
                    collapsible = TRUE,
                    collapsed = TRUE),
                box(DT::dataTableOutput("tabla_bajo_lim_teo_prop"),
                    title = "Personas Bajo Piso en límites propuestos",
                    width = 12,
                    status = "success",
                    solidHeader = F,
                    collapsible = TRUE,
                    collapsed = TRUE),
                box(DT::dataTableOutput("tabla_sobre_lim_teo_prop"),
                    title = "Personas Sobre Piso en límites propuestos",
                    width = 12,
                    status = "success",
                    solidHeader = F,
                    collapsible = TRUE,
                    collapsed = TRUE),
                box(plotlyOutput("multihistPlot", height = 275),
                    title = paste0("Histogramas: Facturación Anual según nivel"),
                    width = 12,
                    status = "info",
                    solidHeader = TRUE)
                )
              )
    ))
    
  )
)



